apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-search-frontend
  namespace: flight-search-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-search-frontend
  template:
    metadata:
      labels:
        app: flight-search-frontend
    spec:
      containers:
      - name: frontend
        image: flight-search/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flight-search-frontend-service
  namespace: flight-search-prod
spec:
  selector:
    app: flight-search-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flight-search-frontend-hpa
  namespace: flight-search-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flight-search-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70